# 数据源配置
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password:
#        slave_1:
#          url: jdbc:mysql://xx.xx.xx.xx:3307/dynamic
#          username: root
#          password: 123456
      druid:
        initialSize: 5
        minIdle: 10
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'X' "
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        filters: stat,slf4j,wall
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:
        enabled: true #按实际情况修改
        allow: ""
        url-pattern: /druid/*
        reset-enable: true
        login-username: ruoyi
        login-password: 123456
      filter:
        wall:
          config:
            multi-statement-allow: true
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰自动映射
    cache-enabled: false
  type-aliases-package: com.ruoyi.**.domain,com.ruoyi.common.core.domain.entity
